#!/usr/bin/env ruby

## 'chrome_lnchr' ##

# Later, handle multiple mode in opening chrome
## new window
## new tab
## private window
## open google services (gmail, hangouts and stuff)

HOST_OS ||= (defined?('RbConfig') ? RbConfig : Config)::CONFIG['host_os']

# troll. useless here
def windows?
  !!HOST_OS.match(/mswin|windows|cygwin/i)
end

def osx?
  !!HOST_OS.match(/darwin/i)
end

def linux?
  !!HOST_OS.match(/linux/i)
end

def host_os
  [:windows, :osx, :linux].find { |os| send(:"#{os}?") }
end

def main
  ## main method of program. run first

end

if __FILE__ == $0
  # Do something.. run tests, call a method, etc. We're direct.

  main
end

