#!/bin/bash

## 'config_ubuntu' ##
# Script by GUEYE Babacar

# Quick installtion of my ubuntu development machine.
# Inspired by thoughtbot/laptop project on github (https://github.com/thoughtbot/laptop/)

PACKAGES=( 'git' 'zsh' 'emacs24-nox' 'vim' )

fancy_echo() {
  local fmt="$1"; shift
  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}
append_to_zshrc() {
  local text="$1" zshrc
  local skip_new_line="$2"
  if [ -w "$HOME/.zshrc.local" ]; then
    zshrc="$HOME/.zshrc.local"
  else
    zshrc="$HOME/.zshrc"
  fi
  if ! grep -Fqs "$text" "$zshrc"; then
    if [ "$skip_new_line" -eq 1 ]; then
      printf "%s\n" "$text" >> "$zshrc"
    else
      printf "\n%s\n" "$text" >> "$zshrc"
    fi
  fi
}

trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
set -e

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi
if [ ! -f "$HOME/.zshrc" ]; then
  touch "$HOME/.zshrc"
fi
# shellcheck disable=SC2016
append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'
case "$SHELL" in
  */zsh) : ;;
  *)
  fancy_echo "Changing your shell to zsh ..."
  chsh -s "$(which zsh)"
  ;;
esac

for pkg in ${PACKAGES[@]}
do
  echo $pkg
done
