#!/bin/bash

# if option --test = true // add method test and format name accordingly

for var in "$@"
do
    echo ">> $var"
    cat << EOF > $var
#!/usr/bin/env ruby

## '$var' ##

def main
  puts "$var"
end

if __FILE__ == \$0
  main
end

EOF
    chmod +x $var
done
