#!/bin/bash

for var in "$@"
do
    echo ">> $var"
    cat << EOF > $var
#!/usr/bin/env python3

## '$var' ##

def main():
    print "$var"

if __name__ == '__main__':
    main()
EOF
    chmod +x $var
done
