#!/bin/bash

function write_files()
{
    cat << EOF > $1/my_app.rb
require 'sinatra'
require "better_errors"

# configuration

configure :development do
  use BetterErrors::Middleware
  BetterErrors.application_root = __dir__
end

# routes

get '/' do
  "Hello World"
end

get '/fail' do
  raise 'oops'
end
EOF

    cat << EOF > $1/Gemfile
source 'https://rubygems.org'
ruby '2.1.1'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'httparty'
gem 'haml'

group :development do
  gem 'betters_errors'
end
EOF

    cat << EOF > $1/config.ru
\$LOAD_PATH << '.'
require 'my_app'

run Sinatra::Application
EOF

    cat << EOF > $1/Procfile
web: bundle exec rackup config.ru -p \$PORT
EOF
}

if [ $# -eq 0 ]
then
    echo -e "\033[31m"
    echo "No arguments detected"
    echo -e "\033[37m"
    echo "Using default name ..."
    mkdir -p myproject myproject/views myproject/lib myproject/public myproject/public/javascript myproject/public/css myproject/public/images
    
    write_files "myproject"

else
    mkdir -p $1 $1/views $1/lib $1/public $1/public/javascript $1/public/css $1/public/images
    
    write_files $1
fi

echo "Finished. Have fun !"